import path from 'path';
import { promises as fs, constants as FS } from 'fs';
import * as XLSX from 'xlsx';

function pascalCase(name: string): string {
  return name
    .split(/[^A-Za-z0-9]+/g)
    .filter(Boolean)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}
function mapTsType(t?: string): 'number' | 'string' {
  return (t || '').trim().toLowerCase() === 'number' ? 'number' : 'string';
}

async function readHeaderFromXlsx(file: string): Promise<{ types: string[]; keys: string[] } | null> {
  await fs.access(file, FS.R_OK);
  const buf = await fs.readFile(file);
  const wb = XLSX.read(buf, { type: 'buffer', cellDates: false });
  const ws = wb.Sheets[wb.SheetNames[0]];
  if (!ws) return null;
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1, raw: true }) as any[][];
  if (!rows || rows.length < 3) return null;
  const types = (rows[1] || []).map(v => (v == null ? '' : String(v).trim().toLowerCase()));
  const keys  = (rows[2] || []).map(v => (v == null ? '' : String(v).trim()));
  if (!keys.some(k => k.toLowerCase() === 'id')) return null;
  return { types, keys };
}

function genInterfaceCode(iface: string, types: string[], keys: string[]) {
  const fields: string[] = [];
  for (let i = 0; i < keys.length; i++) {
    const k = keys[i];
    if (!k) continue;
    fields.push(`    ${k}: ${mapTsType(types[i])};`);
  }
  return `export interface ${iface} extends ITableModel {\n${fields.join('\n')}\n}\n`;
}

/**
 * 读取 excelDir 下的 .xlsx，合并生成 TableModel.ts
 * - 第1行: 注释
 * - 第2行: 类型(number/string)
 * - 第3行: 键名(必须包含 id)
 */
export async function generateModels(
  excelDir: string,
  outFile: string,
  options?: { importPath?: string }
): Promise<{ outFile: string; count: number }> {
  const importPath = options?.importPath ?? '../../CHFramework/Framework';

  const files = (await fs.readdir(excelDir))
    .filter(f => f.toLowerCase().endsWith('.xlsx') && !f.startsWith('~$'))
    .map(f => path.join(excelDir, f))
    .sort((a, b) => path.parse(a).name.localeCompare(path.parse(b).name, 'en', { sensitivity: 'base' }));

  const pieces: string[] = [];
  for (const f of files) {
    try {
      const header = await readHeaderFromXlsx(f);
      if (!header) {
        console.warn(`[excel2model] 跳过（无表头/缺少 id）: ${path.basename(f)}`);
        continue;
      }
      const iface = `I${pascalCase(path.parse(f).name)}`;
      pieces.push(genInterfaceCode(iface, header.types, header.keys));
    } catch (e: any) {
      console.warn(`[excel2model] 跳过（无法读取）: ${f} -> ${e?.message || e}`);
    }
  }

  if (!pieces.length) {
    console.warn('[excel2model] 无可生成的接口');
    await fs.mkdir(path.dirname(outFile), { recursive: true });
    await fs.writeFile(
      outFile,
      `import { ITableModel } from "${importPath}";\n/** AUTO-GENERATED: EMPTY */\n`,
      'utf8'
    );
    return { outFile, count: 0 };
  }

  const content = [
    `import { ITableModel } from "${importPath}";`,
    '/**',
    ' * AUTO-GENERATED, DO NOT MODIFY IT.',
    ' * Generated by: CHFramework',
    ' */',
    '',
    ...pieces,
  ].join('\n');

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, content, 'utf8');
  console.log(`[excel2model] 生成: ${outFile} (${pieces.length})`);
  return { outFile, count: pieces.length };
}