/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
  }
}
declare module 'electron' {
  export const dialog: {
    showOpenDialog: (options: {
      title?: string;
      defaultPath?: string;
      properties?: string[];
    }) => Promise<{ canceled: boolean; filePaths: string[] }>;
  };
}